<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# instrscan

```go
import "github.com/hoangharry-tm/zerotrust/internal/pattern/instrscan"
```

Package instrscan implements the AI agent instruction file scanner \(Approach 1 deliverable\). It is the only tool that scans MCP server configs, .cursor/rules, AGENTS.md, CLAUDE.md, GEMINI.md, and copilot\-instructions.md for prompt injection signals. Three tiers, zero\-to\-low model cost:

```
Tier 1 -- Unicode obfuscation scan + keyword match + MCP JSON schema validation
Tier 2 -- Embedding similarity (Python worker, Approach 2+)
Tier 3 -- Sandboxed LLM meta-audit (Python worker, Approach 2+)
```

## Index

- [type Finding](<#Finding>)
- [type Scanner](<#Scanner>)
  - [func New\(\) \*Scanner](<#New>)
  - [func \(s \*Scanner\) Scan\(fsys fs.FS\) \(\[\]Finding, error\)](<#Scanner.Scan>)
- [type SignalType](<#SignalType>)


<a name="Finding"></a>
## type [Finding](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/pattern/instrscan/instrscan.go#L32-L41>)

Finding is a single prompt injection signal detected in an instruction file.

```go
type Finding struct {
    // File is the path of the scanned file (relative to the fs.FS root).
    File string
    // Line is the 1-based line number where the signal was detected (0 for file-level signals).
    Line int
    // Signal classifies the detection tier that produced this finding.
    Signal SignalType
    // Detail is a human-readable description of the specific signal.
    Detail string
}
```

<a name="Scanner"></a>
## type [Scanner](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/pattern/instrscan/instrscan.go#L44>)

Scanner walks an fs.FS and detects prompt injection signals in AI agent instruction files.

```go
type Scanner struct{}
```

<a name="New"></a>
### func [New](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/pattern/instrscan/instrscan.go#L47>)

```go
func New() *Scanner
```

New returns a Scanner ready to walk an fs.FS.

<a name="Scanner.Scan"></a>
### func \(\*Scanner\) [Scan](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/pattern/instrscan/instrscan.go#L120>)

```go
func (s *Scanner) Scan(fsys fs.FS) ([]Finding, error)
```

Scan walks fsys and returns all prompt injection findings across instruction files and MCP configs.

<a name="SignalType"></a>
## type [SignalType](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/pattern/instrscan/instrscan.go#L22>)

SignalType classifies the kind of prompt injection signal detected in an instruction file.

```go
type SignalType string
```

<a name="SignalUnicodeObfuscation"></a>SignalType constants for the three detection tiers.

```go
const (
    SignalUnicodeObfuscation SignalType = "unicode_obfuscation"  // invisible/bidi Unicode characters
    SignalKeywordMatch       SignalType = "keyword_match"        // suspicious keyword phrase match
    SignalMCPSchemaViolation SignalType = "mcp_schema_violation" // over-broad MCP server permission
)
```

Generated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)
