<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# classifier

```go
import "github.com/hoangharry-tm/zerotrust/internal/semantic/classifier"
```

Package classifier wraps the UniXcoder\-Base\-Nine vulnerability classifier \(Path B Tier 2\) via the Python worker IPC boundary.

UniXcoder\-Base\-Nine \(\~125M parameters, CPU\-only\) is a code understanding model fine\-tuned on BigVul. It gates surfaces before the expensive LLM reasoning tier, targeting \~75–85% elimination of surfaces that reach this stage.

A\-18 blocking dependency: BigVul F1 is measured on C/C\+\+ data and is not a valid claim for Python / Java / JS / Go. CVEFixes fine\-tuning and per\-language benchmark validation are required before publishing accuracy figures. Until then the classifier operates in high\-recall mode \(low classification threshold\).

Language support:

- Supported \(classifier runs\): Python, Java, JavaScript/TypeScript, Go, Ruby, PHP.
- Unsupported \(routed directly to LLM\): Rust, Kotlin, Swift, C\#.

IDOR escalation: surfaces marked IsIDORCandidate always escalate to the LLM tier regardless of the classifier verdict.

## Index

- [func IsSupported\(lang string\) bool](<#IsSupported>)
- [type Gate](<#Gate>)
  - [func New\(w \*worker.Manager\) \*Gate](<#New>)
  - [func NewWithThreshold\(w \*worker.Manager, threshold float64\) \*Gate](<#NewWithThreshold>)
  - [func \(g \*Gate\) Classify\(ctx context.Context, surfaces \[\]enrichment.EnrichedSurface\) \(\[\]Result, error\)](<#Gate.Classify>)
- [type Label](<#Label>)
- [type Result](<#Result>)
- [type SupportedLanguage](<#SupportedLanguage>)


<a name="IsSupported"></a>
## func [IsSupported](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/classifier/classifier.go#L124>)

```go
func IsSupported(lang string) bool
```

IsSupported reports whether the classifier supports the given language. Unsupported languages are routed directly to the LLM tier.

Parameters:

- lang: the source language string \(e.g. "go", "python", "rust"\).

<a name="Gate"></a>
## type [Gate](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/classifier/classifier.go#L74-L80>)

Gate applies the UniXcoder classifier to a batch of surfaces.

```go
type Gate struct {
    // contains filtered or unexported fields
}
```

<a name="New"></a>
### func [New](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/classifier/classifier.go#L86>)

```go
func New(w *worker.Manager) *Gate
```

New returns a Gate backed by the Python worker with a default escalation threshold of 0.80.

Parameters:

- w: the shared Python worker manager.

<a name="NewWithThreshold"></a>
### func [NewWithThreshold](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/classifier/classifier.go#L95>)

```go
func NewWithThreshold(w *worker.Manager, threshold float64) *Gate
```

NewWithThreshold returns a Gate with a custom escalation confidence threshold.

Parameters:

- w: the shared Python worker manager.
- threshold: confidence below which verdicts are treated as uncertain \(0.0–1.0\).

<a name="Gate.Classify"></a>
### func \(\*Gate\) [Classify](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/classifier/classifier.go#L114>)

```go
func (g *Gate) Classify(ctx context.Context, surfaces []enrichment.EnrichedSurface) ([]Result, error)
```

Classify classifies each surface and returns one Result per input surface.

Routing rules applied in order:

1. If surface.IsIDORCandidate → Escalate=true, EscalateReason="idor\_candidate".
2. If surface language is unsupported → Escalate=true, EscalateReason="unsupported\_language".
3. Run UniXcoder; if confidence \< escalationThreshold → Label=LabelUncertain, Escalate=true.
4. If Label=LabelSafe and confidence ≥ threshold → Escalate=false \(surface exits Path B\).

Parameters:

- ctx: cancellation context.
- surfaces: the enriched surfaces from the enrichment stage.

Returns:

- \[\]Result: one result per input surface, in the same order.
- error: non\-nil only for worker communication failures.

<a name="Label"></a>
## type [Label](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/classifier/classifier.go#L29>)

Label is the 3\-band classification output.

```go
type Label string
```

<a name="LabelVulnerable"></a>

```go
const (
    // LabelVulnerable means the classifier predicts the surface is vulnerable.
    LabelVulnerable Label = "vulnerable"
    // LabelSafe means the classifier predicts the surface is not vulnerable.
    // High-confidence safe verdicts skip LLM entirely and are emitted as LOW or suppressed.
    LabelSafe Label = "safe"
    // LabelUncertain means the classifier confidence is below the escalation threshold.
    // Uncertain surfaces are forwarded to the Call Chain Assembler + LLM tier.
    LabelUncertain Label = "uncertain"
)
```

<a name="Result"></a>
## type [Result](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/classifier/classifier.go#L58-L71>)

Result is the classifier output for one surface.

```go
type Result struct {
    // SurfaceID matches the input enrichment.EnrichedSurface.ID.
    SurfaceID string
    // Label is the 3-band classification.
    Label Label
    // Confidence is the model's softmax probability for the winning label (0.0–1.0).
    Confidence float64
    // Escalate is true when the surface must proceed to the LLM tier regardless
    // of Label (IDOR candidate, unsupported language, or uncertain verdict).
    Escalate bool
    // EscalateReason describes why Escalate is true ("idor_candidate",
    // "unsupported_language", "uncertain").
    EscalateReason string
}
```

<a name="SupportedLanguage"></a>
## type [SupportedLanguage](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/classifier/classifier.go#L44>)

SupportedLanguage is the set of languages the UniXcoder classifier handles. Languages not in this set are always routed directly to the LLM tier.

```go
type SupportedLanguage string
```

<a name="LangPython"></a>SupportedLanguage constants for languages handled by the UniXcoder classifier.

```go
const (
    LangPython     SupportedLanguage = "python"
    LangJava       SupportedLanguage = "java"
    LangJavaScript SupportedLanguage = "javascript"
    LangTypeScript SupportedLanguage = "typescript"
    LangGo         SupportedLanguage = "go"
    LangRuby       SupportedLanguage = "ruby"
    LangPHP        SupportedLanguage = "php"
)
```

Generated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)
