<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# llmscan

```go
import "github.com/hoangharry-tm/zerotrust/internal/semantic/llmscan"
```

Package llmscan implements the LLM Semantic Scan \(Path B Tier 3\).

The Scanner receives ranked semantic summaries — never raw source code — and runs a bounded ReAct loop \(max 3 steps\) per surface via the Python worker. Path A HIGH/BLOCK findings are not passed to this stage; it operates only on surfaces that reached Tier 3 through the Path B cost funnel.

ReAct loop \(VULSOLVER pattern, max 3 steps\):

- Step 1 \(Reconnaissance\): identify taint flows, auth patterns, IDOR signals.
- Step 2 \(Exploitation\): model whether identified signals constitute an exploitable flaw.
- Step 3 \(Verification\): apply progressive constraints to reduce false positives. Semantic exit conditions allow early termination when confidence is high.

Backbone capability check: before the first surface is processed, a structured JSON probe is sent. If the model fails to return valid JSON within two attempts, the scan downgrades to single\-pass CoD\+SCoT for all surfaces in this run.

Uncertain verdicts are emitted as SUPPRESSED findings with SuppressReasonUncertain. They are never silently dropped.

Approach 3 replaces the single LLM with a 3\-agent ensemble: Reconnaissance Agent → Exploitation Agent → Verification Agent \(LangGraph\).

Scan Security Context Store: after each surface is processed, the Scanner writes inferences to the SCS store. The store is queried for accumulated context before analysing each subsequent surface, enabling cross\-surface vulnerability detection \(RepoAudit ICML 2025 memoization pattern\).

## Index

- [type ReActStep](<#ReActStep>)
- [type ScanMode](<#ScanMode>)
- [type ScanResult](<#ScanResult>)
- [type Scanner](<#Scanner>)
  - [func New\(w \*worker.Manager\) \*Scanner](<#New>)
  - [func \(s \*Scanner\) BackboneCheck\(ctx context.Context\) \(ScanMode, error\)](<#Scanner.BackboneCheck>)
  - [func \(s \*Scanner\) Scan\(ctx context.Context, surfaces \[\]budget.RankedSurface\) \(\[\]finding.Finding, error\)](<#Scanner.Scan>)
  - [func \(s \*Scanner\) WithStore\(store \*scs.Store\) \*Scanner](<#Scanner.WithStore>)


<a name="ReActStep"></a>
## type [ReActStep](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/llmscan/llmscan.go#L50-L59>)

ReActStep is one reasoning step in the bounded ReAct loop.

```go
type ReActStep struct {
    // StepNum is 1, 2, or 3.
    StepNum int
    // Thought is the model's reasoning for this step.
    Thought string
    // Action describes what the model is checking in this step.
    Action string
    // Observation is the model's conclusion from the action.
    Observation string
}
```

<a name="ScanMode"></a>
## type [ScanMode](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/llmscan/llmscan.go#L40>)

ScanMode controls whether the ReAct loop or single\-pass fallback is used.

```go
type ScanMode string
```

<a name="ScanModeReAct"></a>

```go
const (
    // ScanModeReAct uses the full 3-step bounded ReAct loop (default).
    ScanModeReAct ScanMode = "react"
    // ScanModeSinglePass uses single-pass CoD+SCoT (backbone capability check failed).
    ScanModeSinglePass ScanMode = "single_pass"
)
```

<a name="ScanResult"></a>
## type [ScanResult](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/llmscan/llmscan.go#L62-L79>)

ScanResult is the per\-surface output of the LLM Semantic Scan.

```go
type ScanResult struct {
    // SurfaceID matches the input budget.RankedSurface.SurfaceID.
    SurfaceID string
    // Verdict is the final classification: "vulnerable" | "safe" | "uncertain".
    Verdict string
    // Confidence is the model's self-reported confidence score (0.0–1.0).
    Confidence float64
    // Justification is the final 1–3 sentence explanation.
    Justification string
    // CWE is the CWE identifier identified by the LLM (may refine the classifier's CWE).
    CWE string
    // Steps are the ReAct reasoning steps taken (empty in single-pass mode).
    Steps []ReActStep
    // Mode indicates whether ReAct or single-pass was used.
    Mode ScanMode
    // EarlyExit is true when a semantic exit condition allowed termination before step 3.
    EarlyExit bool
}
```

<a name="Scanner"></a>
## type [Scanner](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/llmscan/llmscan.go#L82-L87>)

Scanner runs the bounded ReAct LLM scan over ranked surfaces.

```go
type Scanner struct {
    // contains filtered or unexported fields
}
```

<a name="New"></a>
### func [New](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/llmscan/llmscan.go#L94>)

```go
func New(w *worker.Manager) *Scanner
```

New returns a Scanner backed by the Python worker. store is the per\-scan SCS store; pass scs.New\(\) from the pipeline orchestrator.

Parameters:

- w: the shared Python worker manager.

<a name="Scanner.BackboneCheck"></a>
### func \(\*Scanner\) [BackboneCheck](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/llmscan/llmscan.go#L143>)

```go
func (s *Scanner) BackboneCheck(ctx context.Context) (ScanMode, error)
```

BackboneCheck probes the Python worker to verify the configured model can produce valid structured JSON output. Returns the ScanMode to use for the full scan.

Parameters:

- ctx: cancellation context.

Returns:

- ScanMode: ScanModeReAct if the model passes, ScanModeSinglePass if it fails.
- error: non\-nil only for worker communication failures \(not JSON parse failures\).

<a name="Scanner.Scan"></a>
### func \(\*Scanner\) [Scan](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/llmscan/llmscan.go#L129>)

```go
func (s *Scanner) Scan(ctx context.Context, surfaces []budget.RankedSurface) ([]finding.Finding, error)
```

Scan runs the bounded ReAct loop \(or single\-pass fallback\) for each surface and returns normalised findings.

Processing order:

1. Backbone capability check \(one per Scan call, not per surface\).
2. For each surface \(callee\-first order from budget.Rank\): a. Query SCS store for accumulated context from prior surfaces. b. Run the ReAct loop \(or single\-pass\) via the Python worker. c. Write inferences to the SCS store. d. Normalise the ScanResult into a finding.Finding.

Uncertain surfaces are emitted as SUPPRESSED with SuppressReasonUncertain.

Parameters:

- ctx: cancellation context; honours deadline across all surface scans.
- surfaces: the ranked surface list from the Token Budget Controller.

Returns:

- \[\]finding.Finding: one finding per surface \(uncertain → SUPPRESSED\).
- error: non\-nil only for unrecoverable worker communication failures.

<a name="Scanner.WithStore"></a>
### func \(\*Scanner\) [WithStore](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/semantic/llmscan/llmscan.go#L104>)

```go
func (s *Scanner) WithStore(store *scs.Store) *Scanner
```

WithStore attaches a Scan Security Context Store to the Scanner. Call this before Scan when cross\-surface vulnerability detection is needed. If not called, the Scanner operates without accumulated context.

Parameters:

- store: the per\-scan SCS store created by the pipeline orchestrator.

Generated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)
