<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# diffindex

```go
import "github.com/hoangharry-tm/zerotrust/internal/ingestion/diffindex"
```

Package diffindex implements the Differential Indexer.

The Indexer compares the current file set against a SQLite state cache and returns only files that are new or changed since the last scan, reducing per\-scan cost of OpenGrep, Joern CPG build, and Path B by \~80–95%.

Content hashing: each file is hashed with SHA\-256; only files whose hash differs from the cached value are considered changed. Deleted files appear in ChangeSet.Removed so downstream stages can evict their CPG nodes.

First scan: no rows exist in the cache, so all files are returned as Changed. Repeat scan: only new / modified / deleted files appear in the ChangeSet.

## Index

- [func DeriveProjectID\(projectRoot string\) string](<#DeriveProjectID>)
- [type ChangeSet](<#ChangeSet>)
- [type FileState](<#FileState>)
- [type Indexer](<#Indexer>)
  - [func New\(db \*sqlite.DB\) \*Indexer](<#New>)
  - [func \(i \*Indexer\) Commit\(ctx context.Context, projectID string, states \[\]FileState\) error](<#Indexer.Commit>)
  - [func \(i \*Indexer\) Diff\(ctx context.Context, projectID, projectRoot string\) \(\*ChangeSet, error\)](<#Indexer.Diff>)


<a name="DeriveProjectID"></a>
## func [DeriveProjectID](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/diffindex/diffindex.go#L95>)

```go
func DeriveProjectID(projectRoot string) string
```

DeriveProjectID returns a deterministic project identifier from the absolute project root path. Used when the caller does not supply an explicit \-\-project\-id flag.

The returned value is the first 16 hex characters of SHA\-256\(projectRoot\), giving a compact and collision\-resistant key suitable for SQLite primary keys.

Parameters:

- projectRoot: absolute path to the codebase root.

<a name="ChangeSet"></a>
## type [ChangeSet](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/diffindex/diffindex.go#L37-L45>)

ChangeSet is the output of a differential comparison.

```go
type ChangeSet struct {
    // Changed holds the relative paths of files that are new or modified.
    // Both detection paths consume this list as their input file set.
    Changed []string
    // Removed holds the relative paths of files present in the prior scan
    // but absent from the current file set. The Joern incremental CPG patch
    // must evict their nodes before running taint queries.
    Removed []string
}
```

<a name="FileState"></a>
## type [FileState](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/diffindex/diffindex.go#L25-L34>)

FileState records the cached state of one file from a prior scan.

```go
type FileState struct {
    // ProjectID identifies the owning project (matches sqlite.ScanStateRow.ProjectID).
    ProjectID string
    // FilePath is the path relative to the project root.
    FilePath string
    // ContentHash is the SHA-256 hex digest of the file's contents.
    ContentHash string
    // LastScannedAt is the Unix timestamp (seconds) of the scan that last wrote this row.
    LastScannedAt int64
}
```

<a name="Indexer"></a>
## type [Indexer](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/diffindex/diffindex.go#L48-L50>)

Indexer computes the differential file set for each scan.

```go
type Indexer struct {
    // contains filtered or unexported fields
}
```

<a name="New"></a>
### func [New](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/diffindex/diffindex.go#L53>)

```go
func New(db *sqlite.DB) *Indexer
```

New returns an Indexer backed by db.

<a name="Indexer.Commit"></a>
### func \(\*Indexer\) [Commit](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/diffindex/diffindex.go#L82>)

```go
func (i *Indexer) Commit(ctx context.Context, projectID string, states []FileState) error
```

Commit persists the current file states for projectID, replacing any prior state. Call this after a successful scan to advance the cache baseline for the next run.

Parameters:

- ctx: cancellation context.
- projectID: primary\-key prefix for the SQLite scan\_state table.
- states: the complete current file\-state list \(one entry per file in scope\).

<a name="Indexer.Diff"></a>
### func \(\*Indexer\) [Diff](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/diffindex/diffindex.go#L70>)

```go
func (i *Indexer) Diff(ctx context.Context, projectID, projectRoot string) (*ChangeSet, error)
```

Diff walks projectRoot, hashes every file, and compares against the cached state for projectID in SQLite. Returns the ChangeSet for this scan.

On first scan \(no cache rows\) all files are returned as Changed.

Parameters:

- ctx: cancellation context; long directory walks honour it between subdirectories.
- projectID: primary\-key prefix for the SQLite scan\_state table.
- projectRoot: absolute path to the codebase root to walk.

Returns:

- \*ChangeSet: Changed \(new/modified\) and Removed \(deleted\) file sets.
- error: non\-nil if projectRoot cannot be walked or SQLite access fails.

Generated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)
