<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# miv

```go
import "github.com/hoangharry-tm/zerotrust/internal/ingestion/miv"
```

Package miv implements the Model Integrity Verifier.

At startup MIV hashes the local GGUF model file and verifies it against a cosign/Sigstore Rekor signed registry. The registry is a JSON file bundled with the binary, signed with a project\-controlled key whose public half is embedded at build time.

Tiered response \(ICML 2025 GGUF backdoor threat model\):

- PASS: known model ID, hash matches the signed registry entry → LLM proceeds.
- WARN: unrecognised model ID \(user's own model\) → LLM proceeds after user opt\-in.
- BLOCK: known model ID, hash mismatch → all LLM calls are skipped; CPG and pattern matching continue unaffected.

MIV gates only LLM invocations. Joern CPG builds, OpenGrep / ast\-grep pattern scans, and the HTML report are never blocked.

## Index

- [type RegistryEntry](<#RegistryEntry>)
- [type Result](<#Result>)
- [type Status](<#Status>)
- [type Verifier](<#Verifier>)
  - [func New\(registryPath, publicKeyPath string\) \*Verifier](<#New>)
  - [func \(v \*Verifier\) LoadRegistry\(ctx context.Context\) \(\[\]RegistryEntry, error\)](<#Verifier.LoadRegistry>)
  - [func \(v \*Verifier\) Verify\(ctx context.Context, modelPath string\) \(\*Result, error\)](<#Verifier.Verify>)


<a name="RegistryEntry"></a>
## type [RegistryEntry](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/miv/miv.go#L57-L66>)

RegistryEntry is one record in the signed JSON model hash registry.

Example registry entry:

```
{
  "model_id": "llama3.2:3b-instruct-q4_K_M",
  "sha256":   "a3f7c...",
  "source":   "https://ollama.com/library/llama3.2",
  "added_at": "2025-09-01"
}
```

```go
type RegistryEntry struct {
    // ModelID is the Ollama model tag (e.g. "llama3.2:3b-instruct-q4_K_M").
    ModelID string `json:"model_id"`
    // SHA256 is the expected SHA-256 hex digest of the GGUF file.
    SHA256 string `json:"sha256"`
    // Source is the canonical download URL for the model.
    Source string `json:"source"`
    // AddedAt is the ISO-8601 date when the entry was added to the registry.
    AddedAt string `json:"added_at"`
}
```

<a name="Result"></a>
## type [Result](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/miv/miv.go#L34-L45>)

Result is returned by Verify.

```go
type Result struct {
    // Status is the tiered outcome (PASS / WARN / BLOCK).
    Status Status
    // ModelID is the identifier extracted from the GGUF metadata header.
    ModelID string
    // ActualHash is the SHA-256 hex digest of the model file that was checked.
    ActualHash string
    // ExpectedHash is the hash from the signed registry (empty for WARN/unrecognised).
    ExpectedHash string
    // Message is a human-readable description of the outcome, shown in the report header.
    Message string
}
```

<a name="Status"></a>
## type [Status](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/miv/miv.go#L21>)

Status is the tiered verification outcome.

```go
type Status string
```

<a name="StatusPass"></a>

```go
const (
    // StatusPass means the model is known and its hash matches the signed registry.
    StatusPass Status = "PASS"
    // StatusWarn means the model ID is unrecognised; user opt-in is required.
    StatusWarn Status = "WARN"
    // StatusBlock means the model ID is known but its hash mismatches the registry.
    // All LLM invocations must be skipped when this status is returned.
    StatusBlock Status = "BLOCK"
)
```

<a name="Verifier"></a>
## type [Verifier](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/miv/miv.go#L69-L74>)

Verifier hashes the GGUF model file and compares it against the signed registry.

```go
type Verifier struct {
    // contains filtered or unexported fields
}
```

<a name="New"></a>
### func [New](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/miv/miv.go#L82>)

```go
func New(registryPath, publicKeyPath string) *Verifier
```

New returns a Verifier using the bundled registry and public key at the given paths. Passing empty strings causes the embedded defaults to be used \(resolved in G2.M2.2\).

Parameters:

- registryPath: path to the signed model hash registry JSON file.
- publicKeyPath: path to the cosign public key \(.pub\) for registry verification.

<a name="Verifier.LoadRegistry"></a>
### func \(\*Verifier\) [LoadRegistry](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/miv/miv.go#L118>)

```go
func (v *Verifier) LoadRegistry(ctx context.Context) ([]RegistryEntry, error)
```

LoadRegistry reads and verifies the signature of the registry at v.registryPath and returns its entries. Returns an error if the signature is invalid.

Parameters:

- ctx: cancellation context.

Returns:

- \[\]RegistryEntry: all entries in the verified registry.
- error: non\-nil if the file is unreadable or the cosign signature fails.

<a name="Verifier.Verify"></a>
### func \(\*Verifier\) [Verify](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/ingestion/miv/miv.go#L104>)

```go
func (v *Verifier) Verify(ctx context.Context, modelPath string) (*Result, error)
```

Verify runs the full integrity check pipeline for the model at modelPath:

1. SHA\-256 hash the GGUF file.
2. Verify the registry file's cosign/Rekor signature.
3. Look up the model ID \(from GGUF metadata\) in the verified registry.
4. Compare the actual hash against the registry entry.

WARN does not block; BLOCK stops all LLM invocations.

Parameters:

- ctx: cancellation context; hashing a large GGUF file may take several seconds.
- modelPath: absolute path to the GGUF model file on disk.

Returns:

- \*Result: the verification outcome with status, hashes, and message.
- error: non\-nil only for infrastructure failures \(file unreadable, registry malformed\).

Generated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)
