<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# dedup

```go
import "github.com/hoangharry-tm/zerotrust/internal/dedup"
```

Package dedup implements the Dedup \+ Confidence Scoring layer.

The Layer receives findings from both detection paths, deduplicates them through a cost\-cascaded 4\-gate strategy, applies SSVC\-inspired confidence scoring, and emits a scored finding set for the HTML report and PoE layer.

Dedup gate cascade \(cheapest first — later gates are only invoked when prior gates do not produce a match\):

1. CWE hash \+ file path \+ line range overlap \(O\(1\), exact match\).
2. Code snippet SHA\-256 fingerprint \(O\(1\), exact match on MatchedCode\).
3. Embedding cosine similarity via MiniLM\-L6\-v2 \(Python worker, \~0.5 ms/pair\).
4. AST edit distance via Zhang\-Shasha \(last resort, expensive\).

Cross\-path boost: when Path A and Path B independently confirm the same finding \(merged SourcePath becomes BOTH\), confidence receives a \+15 pp additive boost, capped at 1.0.

Auto\-suppression: findings in test file patterns or under framework\-safe library paths are suppressed without LLM involvement. The SuppressReason field is always set; no finding is ever silently dropped.

SSVC dimension sourcing:

- Exploitation: CISA KEV \+ EPSS \+ NVD \(via Trivy enrichment\).
- Automatable: static CWE→automatable lookup table.
- TechnicalImpact: CVSS base score \+ CWE impact map.

## Index

- [func AutoSuppress\(f finding.Finding\) finding.Finding](<#AutoSuppress>)
- [func DeriveSSVC\(f finding.Finding\) finding.Finding](<#DeriveSSVC>)
- [func DeriveSeverityLabel\(confidence float64\) finding.SeverityLabel](<#DeriveSeverityLabel>)
- [type Layer](<#Layer>)
  - [func New\(\) \*Layer](<#New>)
  - [func \(l \*Layer\) Process\(findings \[\]finding.Finding\) \(\[\]finding.Finding, error\)](<#Layer.Process>)
  - [func \(l \*Layer\) ProcessWithStats\(findings \[\]finding.Finding\) \(\[\]finding.Finding, \[\]MergeRecord, Stats, error\)](<#Layer.ProcessWithStats>)
- [type MergeRecord](<#MergeRecord>)
- [type Stats](<#Stats>)
- [type Strategy](<#Strategy>)


<a name="AutoSuppress"></a>
## func [AutoSuppress](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/dedup/dedup.go#L126>)

```go
func AutoSuppress(f finding.Finding) finding.Finding
```

AutoSuppress applies test\-file and framework\-safe suppression rules to a single finding. Returns the finding with SeverityLabel and SuppressReason updated if suppression applies; returns it unchanged otherwise.

Suppression rules:

- File path matches a test pattern \(e.g. \*\_test.go, test\_\*.py, spec/\*\*\).
- File path is under a known framework\-safe vendor/dependency directory.

Parameters:

- f: the finding to evaluate.

<a name="DeriveSSVC"></a>
## func [DeriveSSVC](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/dedup/dedup.go#L138>)

```go
func DeriveSSVC(f finding.Finding) finding.Finding
```

DeriveSSVC populates the SSVC dimensions on a finding using the CVE lookup tables \(CISA KEV, EPSS, NVD CVSS, CWE automatable/impact maps\).

Parameters:

- f: the finding to score \(modified in\-place\).

Returns the finding with SSVC fields populated.

<a name="DeriveSeverityLabel"></a>
## func [DeriveSeverityLabel](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/dedup/dedup.go#L154>)

```go
func DeriveSeverityLabel(confidence float64) finding.SeverityLabel
```

DeriveSeverityLabel maps a Confidence score to the corresponding SeverityLabel using the fixed threshold table:

```
BLOCK      ≥ 0.92
HIGH     0.75 – 0.91
MEDIUM   0.60 – 0.74
LOW      0.30 – 0.59
SUPPRESSED < 0.30
```

Parameters:

- confidence: the composite confidence score \(0.0–1.0\).

<a name="Layer"></a>
## type [Layer](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/dedup/dedup.go#L71>)

Layer deduplicates and scores the merged finding set from both detection paths.

```go
type Layer struct{}
```

<a name="New"></a>
### func [New](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/dedup/dedup.go#L74>)

```go
func New() *Layer
```

New returns a Layer ready to process findings.

<a name="Layer.Process"></a>
### func \(\*Layer\) [Process](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/dedup/dedup.go#L95>)

```go
func (l *Layer) Process(findings []finding.Finding) ([]finding.Finding, error)
```

Process deduplicates findings through the 4\-gate cascade and applies SSVC\-inspired confidence scoring.

Processing steps:

1. Auto\-suppress findings in test file patterns or framework\-safe paths.
2. Gate 1: group by CWE \+ filepath \+ line range overlap → merge.
3. Gate 2: group survivors by SHA\-256\(MatchedCode\) → merge.
4. Gate 3: embedding similarity ≥ 0.92 \(MiniLM, Python worker\) → merge.
5. Gate 4: AST edit distance \(Zhang\-Shasha, last resort\) → merge.
6. Apply cross\-path \+15 pp confidence boost where SourcePath == BOTH.
7. Derive SeverityLabel from Confidence using the threshold table.
8. Populate SSVC dimensions from the CVE / CWE lookup tables.

Parameters:

- findings: merged finding list from both paths \(Path A \+ Path B\).

Returns:

- \[\]finding.Finding: deduplicated, SSVC\-scored findings.
- error: non\-nil only if the Python worker embedding call fails \(gate 3\).

<a name="Layer.ProcessWithStats"></a>
### func \(\*Layer\) [ProcessWithStats](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/dedup/dedup.go#L111>)

```go
func (l *Layer) ProcessWithStats(findings []finding.Finding) ([]finding.Finding, []MergeRecord, Stats, error)
```

ProcessWithStats is identical to Process but also returns dedup statistics. Use this when the scan report should include dedup metadata.

Parameters:

- findings: merged finding list from both paths.

Returns:

- \[\]finding.Finding: deduplicated, SSVC\-scored findings.
- \[\]MergeRecord: one record per merged pair.
- Stats: aggregate dedup statistics.
- error: non\-nil if the Python worker embedding call fails.

<a name="MergeRecord"></a>
## type [MergeRecord](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/dedup/dedup.go#L46-L56>)

MergeRecord describes how two findings were merged during deduplication.

```go
type MergeRecord struct {
    // KeptID is the finding.Finding.ID of the surviving record.
    KeptID string
    // DroppedID is the finding.Finding.ID of the duplicate that was merged.
    DroppedID string
    // Strategy is the gate that identified the duplicate.
    Strategy Strategy
    // CrossPathBoostApplied is true when one finding was from Path A and the other
    // from Path B, triggering the +15 pp confidence boost.
    CrossPathBoostApplied bool
}
```

<a name="Stats"></a>
## type [Stats](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/dedup/dedup.go#L59-L68>)

Stats describes the dedup pass outcome for reporting in the scan header.

```go
type Stats struct {
    // InputCount is the total number of findings submitted to Process.
    InputCount int
    // OutputCount is the number of unique findings after dedup.
    OutputCount int
    // MergeCount is the number of duplicate pairs that were merged.
    MergeCount int
    // AutoSuppressedCount is the number of findings auto-suppressed by test/framework rules.
    AutoSuppressedCount int
}
```

<a name="Strategy"></a>
## type [Strategy](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/dedup/dedup.go#L32>)

Strategy identifies which dedup gate resolved a duplicate pair.

```go
type Strategy string
```

<a name="StrategyExactKey"></a>

```go
const (
    // StrategyExactKey means gate 1 (CWE + file + line) resolved the duplicate.
    StrategyExactKey Strategy = "exact_key"
    // StrategyFingerprint means gate 2 (SHA-256 of MatchedCode) resolved it.
    StrategyFingerprint Strategy = "fingerprint"
    // StrategyEmbedding means gate 3 (MiniLM embedding similarity) resolved it.
    StrategyEmbedding Strategy = "embedding"
    // StrategyEditDistance means gate 4 (AST edit distance) resolved it.
    StrategyEditDistance Strategy = "edit_distance"
)
```

Generated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)
