<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# worker

```go
import "github.com/hoangharry-tm/zerotrust/internal/worker"
```

Package worker manages the long\-lived Python ML worker subprocess.

All Python\-side operations communicate through this single process boundary:

- LLM Verifier \(Path A\): verifies pattern findings with CoD \+ SCoT reasoning.
- UniXcoder classifier \(Path B Tier 2\): classifies uncertain surfaces.
- Semantic Function Summarizer \(Path B Tier 2\): converts call chains to JSON summaries.
- LLM Semantic Scan \(Path B Tier 3\): runs the bounded ReAct loop.

Transport: newline\-delimited JSON \(NDJSON\) over stdin/stdout. Each request has a unique ID; the worker echoes the ID in its response, allowing concurrent callers to match responses to outstanding requests.

The worker is spawned once at pipeline startup \(Start\) and kept alive for the entire scan. Call Stop when the scan completes to send a shutdown message and wait for the process to exit cleanly.

Message type routing \(worker/main.py dispatcher\):

```
"llm_verify"  → handlers/llm_verify.py   (Path A LLM Verifier)
"classify"    → handlers/classify.py      (UniXcoder classifier)
"summarize"   → handlers/summarize.py     (Semantic Summarizer)
"llm_scan"    → handlers/llm_scan.py      (LLM Semantic Scan)
"ping"        → built-in health check
"shutdown"    → graceful process exit
```

## Index

- [type ClassifyPayload](<#ClassifyPayload>)
- [type ClassifyResult](<#ClassifyResult>)
- [type ClassifySurface](<#ClassifySurface>)
- [type ClassifySurfaceResult](<#ClassifySurfaceResult>)
- [type LLMScanPayload](<#LLMScanPayload>)
- [type Manager](<#Manager>)
  - [func Start\(ctx context.Context, workerPath string\) \(\*Manager, error\)](<#Start>)
  - [func \(m \*Manager\) Call\(ctx context.Context, msgType MessageType, payload any\) \(\*Response, error\)](<#Manager.Call>)
  - [func \(m \*Manager\) Ping\(ctx context.Context\) error](<#Manager.Ping>)
  - [func \(m \*Manager\) Stop\(\) error](<#Manager.Stop>)
- [type MessageType](<#MessageType>)
- [type Request](<#Request>)
- [type Response](<#Response>)
- [type ResponseStatus](<#ResponseStatus>)
- [type SummarizePayload](<#SummarizePayload>)
- [type VerifyPayload](<#VerifyPayload>)
- [type VerifyResult](<#VerifyResult>)


<a name="ClassifyPayload"></a>
## type [ClassifyPayload](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L113-L116>)

ClassifyPayload is the JSON payload for MsgClassify requests. Carries a batch of enriched surfaces for the UniXcoder gate.

```go
type ClassifyPayload struct {
    // Surfaces holds the surface IDs and code snippets to classify.
    Surfaces []ClassifySurface `json:"surfaces"`
}
```

<a name="ClassifyResult"></a>
## type [ClassifyResult](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L129-L132>)

ClassifyResult is the JSON result for MsgClassify responses.

```go
type ClassifyResult struct {
    // Results holds one classification output per input surface.
    Results []ClassifySurfaceResult `json:"results"`
}
```

<a name="ClassifySurface"></a>
## type [ClassifySurface](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L119-L126>)

ClassifySurface is one surface within a ClassifyPayload.

```go
type ClassifySurface struct {
    // SurfaceID matches the enrichment.EnrichedSurface.ID.
    SurfaceID string `json:"surface_id"`
    // Code is the function source code to classify.
    Code string `json:"code"`
    // Language is the source language (e.g. "python", "go").
    Language string `json:"language"`
}
```

<a name="ClassifySurfaceResult"></a>
## type [ClassifySurfaceResult](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L135-L142>)

ClassifySurfaceResult is the classifier output for one surface.

```go
type ClassifySurfaceResult struct {
    // SurfaceID echoes the input surface ID.
    SurfaceID string `json:"surface_id"`
    // Label is "vulnerable" | "safe" | "uncertain".
    Label string `json:"label"`
    // Confidence is the model's softmax score for the winning label.
    Confidence float64 `json:"confidence"`
}
```

<a name="LLMScanPayload"></a>
## type [LLMScanPayload](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L152-L162>)

LLMScanPayload is the JSON payload for MsgLLMScan requests.

```go
type LLMScanPayload struct {
    // SurfaceID identifies the surface being scanned.
    SurfaceID string `json:"surface_id"`
    // Summary is the JSON-serialized summarizer.Summary for this surface.
    Summary json.RawMessage `json:"summary"`
    // PriorContext is accumulated SCS inferences for this surface's neighbours.
    // Empty JSON object ({}) when no prior context is available.
    PriorContext json.RawMessage `json:"prior_context"`
    // Mode is "react" or "single_pass".
    Mode string `json:"mode"`
}
```

<a name="Manager"></a>
## type [Manager](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L165-L167>)

Manager owns the long\-lived Python worker subprocess and serialises all IPC.

```go
type Manager struct {
    // contains filtered or unexported fields
}
```

<a name="Start"></a>
### func [Start](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L179>)

```go
func Start(ctx context.Context, workerPath string) (*Manager, error)
```

Start spawns the Python worker at workerPath, waits for it to be ready \(via a ping/pong handshake\), and returns a Manager.

Parameters:

- ctx: cancellation context; if cancelled, the subprocess is killed.
- workerPath: path to the worker entry point \(e.g. "worker/main.py"\).

Returns:

- \*Manager: ready\-to\-use manager.
- error: non\-nil if the subprocess fails to start or the ping times out.

<a name="Manager.Call"></a>
### func \(\*Manager\) [Call](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L196>)

```go
func (m *Manager) Call(ctx context.Context, msgType MessageType, payload any) (*Response, error)
```

Call sends a typed request to the worker and returns the decoded response. Safe to call from multiple goroutines concurrently; requests are serialised internally before being written to stdin.

Parameters:

- ctx: cancellation context; a cancelled ctx will abort the pending request.
- msgType: the handler routing label \(one of the Msg\* constants\).
- payload: the handler\-specific request payload \(marshalled to JSON\).

Returns:

- \*Response: the decoded response from the Python worker.
- error: non\-nil on ctx cancellation, worker crash, or JSON encode/decode failure.

<a name="Manager.Ping"></a>
### func \(\*Manager\) [Ping](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L205>)

```go
func (m *Manager) Ping(ctx context.Context) error
```

Ping sends a health\-check request and returns nil if the worker is alive.

Parameters:

- ctx: cancellation context.

<a name="Manager.Stop"></a>
### func \(\*Manager\) [Stop](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L212>)

```go
func (m *Manager) Stop() error
```

Stop sends a shutdown message to the worker and waits for the subprocess to exit. It is safe to call Stop even if the worker is already dead.

<a name="MessageType"></a>
## type [MessageType](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L35>)

MessageType is the string label that routes a request to the correct Python handler.

```go
type MessageType string
```

<a name="MsgLLMVerify"></a>

```go
const (
    // MsgLLMVerify routes to the Path A LLM Verifier handler.
    MsgLLMVerify MessageType = "llm_verify"
    // MsgClassify routes to the UniXcoder classifier handler.
    MsgClassify MessageType = "classify"
    // MsgSummarize routes to the Semantic Function Summarizer handler.
    MsgSummarize MessageType = "summarize"
    // MsgLLMScan routes to the LLM Semantic Scan handler.
    MsgLLMScan MessageType = "llm_scan"
    // MsgPing is a built-in health check; the worker responds immediately.
    MsgPing MessageType = "ping"
    // MsgShutdown requests a clean worker process exit.
    MsgShutdown MessageType = "shutdown"
)
```

<a name="Request"></a>
## type [Request](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L63-L70>)

Request is an NDJSON message sent to the Python worker over stdin.

```go
type Request struct {
    // ID is a unique string for matching this request to its response.
    ID  string `json:"id"`
    // Type routes the request to the correct Python handler.
    Type MessageType `json:"type"`
    // Payload is the handler-specific JSON payload.
    Payload json.RawMessage `json:"payload,omitempty"`
}
```

<a name="Response"></a>
## type [Response](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L73-L82>)

Response is an NDJSON message received from the Python worker over stdout.

```go
type Response struct {
    // ID matches the ID of the originating Request.
    ID  string `json:"id"`
    // Status is ResponseOK or ResponseError.
    Status ResponseStatus `json:"status"`
    // Result is the handler-specific JSON result (set when Status == ResponseOK).
    Result json.RawMessage `json:"result,omitempty"`
    // Error is a human-readable error message (set when Status == ResponseError).
    Error string `json:"error,omitempty"`
}
```

<a name="ResponseStatus"></a>
## type [ResponseStatus](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L53>)

ResponseStatus is the status field in a worker Response.

```go
type ResponseStatus string
```

<a name="ResponseOK"></a>

```go
const (
    // ResponseOK means the request was handled successfully.
    ResponseOK ResponseStatus = "ok"
    // ResponseError means the handler encountered an error; Error field is set.
    ResponseError ResponseStatus = "error"
)
```

<a name="SummarizePayload"></a>
## type [SummarizePayload](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L146-L149>)

SummarizePayload is the JSON payload for MsgSummarize requests. Holds a batch of call chains \(up to 5 per request\).

```go
type SummarizePayload struct {
    // Chains is the batch of call chain JSON objects.
    Chains []json.RawMessage `json:"chains"`
}
```

<a name="VerifyPayload"></a>
## type [VerifyPayload](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L86-L97>)

VerifyPayload is the JSON payload for MsgLLMVerify requests. It carries a single finding for false\-positive classification.

```go
type VerifyPayload struct {
    // FindingID is the finding.Finding.ID being verified.
    FindingID string `json:"finding_id"`
    // RuleID is the OpenGrep / ast-grep rule that matched.
    RuleID string `json:"rule_id"`
    // CWE is the CWE identifier from the rule metadata.
    CWE string `json:"cwe"`
    // MatchedCode is the source snippet at the finding location.
    MatchedCode string `json:"matched_code"`
    // Justification is the rule message / LLM context.
    Justification string `json:"justification"`
}
```

<a name="VerifyResult"></a>
## type [VerifyResult](<https://github.com/hoangharry-tm/ZeroTrust.sh/blob/main/internal/worker/worker.go#L100-L109>)

VerifyResult is the JSON result for MsgLLMVerify responses.

```go
type VerifyResult struct {
    // FindingID echoes the input FindingID.
    FindingID string `json:"finding_id"`
    // Verdict is "confirmed" | "false_positive" | "uncertain".
    Verdict string `json:"verdict"`
    // Confidence is the model's self-reported confidence (0.0–1.0).
    Confidence float64 `json:"confidence"`
    // Justification is the CoD reasoning summary.
    Justification string `json:"justification"`
}
```

Generated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)
