research_data = [
    {
        "id": "R.M1",
        "name": "Literature Foundation",
        "type": "MILESTONE",
        "start": "2026-06-09",
        "end": "2026-06-20",
        "o": 20.0, "ml": 41.0, "p": 82.0, "e": 44.33,
        "status": "In Progress",
        "notes": "Read and annotate all 40 catalogued papers across 7 areas. Build paper-to-architecture-component linkage map.",
        "tasks": [
            {"id": "R.M1.T1", "name": "Read and annotate Area 1 (Deep Learning & ML for Vulnerability Detection, ~4 papers) and Area 2 (GNN for Vulnerability Detection, ~6 papers)", "e": 8.67, "status": "In Progress", "notes": ""},
            {"id": "R.M1.T2", "name": "Read and annotate Area 3 (LLM for Code Security Analysis, ~6 papers)", "e": 12.67, "status": "Not Started", "notes": ""},
            {"id": "R.M1.T3", "name": "Read and annotate Area 4 (Hybrid Static Analysis + LLM, ~5 papers) and Area 5 (AI-Generated Code Security & Prompt Injection, ~5 papers)", "e": 10.83, "status": "Not Started", "notes": ""},
            {"id": "R.M1.T4", "name": "Read and annotate Area 6 (Token Cost Optimization, ~4 papers) and Area 7 (Call Graph, Taint Analysis & Code Representations, ~10 papers)", "e": 9.00, "status": "Not Started", "notes": ""},
            {"id": "R.M1.T5", "name": "Build paper-to-architecture-component linkage map: assign each of the 40 papers to >= 1 ZeroTrust.sh component as primary evidence", "e": 3.17, "status": "Not Started", "notes": ""},
        ],
    },
    {
        "id": "R.M2",
        "name": "Architecture Validation Matrix",
        "type": "MILESTONE",
        "start": "2026-06-16",
        "end": "2026-06-27",
        "o": 4.0, "ml": 8.5, "p": 21.0, "e": 9.83,
        "status": "Not Started",
        "notes": "Map every architecture component to >= 1 supporting paper. Flag components with no academic backing as validation gaps.",
        "tasks": [
            {"id": "R.M2.T1", "name": "Map Differential Indexer and all Path A sub-components to >= 1 supporting paper each", "e": 2.33, "status": "Not Started", "notes": ""},
            {"id": "R.M2.T2", "name": "Map Path B three-tier cost funnel to supporting papers with specific claimed performance figures recorded", "e": 2.33, "status": "Not Started", "notes": ""},
            {"id": "R.M2.T3", "name": "Map Dedup layer and 5-tier Confidence Scoring to supporting papers", "e": 1.25, "status": "Not Started", "notes": ""},
            {"id": "R.M2.T4", "name": "Map Proof-of-Exploit Layer to supporting papers on automated vulnerability verification", "e": 1.75, "status": "Not Started", "notes": ""},
            {"id": "R.M2.T5", "name": "Identify every architecture component with zero academic backing and document each as an open validation gap", "e": 2.17, "status": "Not Started", "notes": ""},
        ],
    },
    {
        "id": "R.M3",
        "name": "Benchmark & Performance Claims Verification",
        "type": "MILESTONE",
        "start": "2026-06-23",
        "end": "2026-07-04",
        "o": 3.0, "ml": 6.5, "p": 18.0, "e": 7.83,
        "status": "Not Started",
        "notes": "Verify every quantitative claim in the architecture docs against its source paper.",
        "tasks": [
            {"id": "R.M3.T1", "name": "Verify UniXcoder-Base-Nine F1=94.73% on BigVul: locate original paper, confirm exact evaluation setup", "e": 1.25, "status": "Not Started", "notes": ""},
            {"id": "R.M3.T2", "name": "Verify 88-93% false positive reduction claim for the LLM Verifier", "e": 1.75, "status": "Not Started", "notes": ""},
            {"id": "R.M3.T3", "name": "Verify ~80-95% cost reduction claim for the Differential Indexer", "e": 1.25, "status": "Not Started", "notes": ""},
            {"id": "R.M3.T4", "name": "Verify ~15-25% LLM escalation rate and ~95% file elimination rate", "e": 1.25, "status": "Not Started", "notes": ""},
            {"id": "R.M3.T5", "name": "Compile benchmarks reference table: claim text, source, confidence level, follow-up action", "e": 2.33, "status": "Not Started", "notes": ""},
        ],
    },
    {
        "id": "R.M4",
        "name": "Competitive Landscape Research",
        "type": "MILESTONE",
        "start": "2026-06-30",
        "end": "2026-07-11",
        "o": 6.0, "ml": 12.0, "p": 26.0, "e": 13.33,
        "status": "Not Started",
        "notes": "Research Semgrep, Snyk Code, and CodeRabbit structural gaps vs ZeroTrust.sh. Compile differentiation evidence table.",
        "tasks": [
            {"id": "R.M4.T1", "name": "Research publicly available accuracy and precision data for Semgrep OSS and Semgrep Pro", "e": 2.33, "status": "Not Started", "notes": ""},
            {"id": "R.M4.T2", "name": "Research Snyk Code architecture with focus on cloud dependency and source-code-upload requirements", "e": 2.17, "status": "Not Started", "notes": ""},
            {"id": "R.M4.T3", "name": "Research CodeRabbit's PR-gated workflow architecture: document what it structurally cannot do", "e": 2.17, "status": "Not Started", "notes": ""},
            {"id": "R.M4.T4", "name": "Search academic databases for evidence that local-only execution with AI-specific threat detection is under-served", "e": 4.50, "status": "Not Started", "notes": ""},
            {"id": "R.M4.T5", "name": "Compile differentiation evidence table: ZeroTrust.sh differentiator, evidence source, competitor, gap type", "e": 2.17, "status": "Not Started", "notes": ""},
        ],
    },
    {
        "id": "R.M5",
        "name": "Architecture Justification Document",
        "type": "MILESTONE",
        "start": "2026-07-07",
        "end": "2026-07-25",
        "o": 6.5, "ml": 13.0, "p": 30.0, "e": 14.75,
        "status": "Not Started",
        "notes": "Formal document linking every major design decision to research evidence. Written for tech lead + stakeholders.",
        "tasks": [
            {"id": "R.M5.T1", "name": "Write Path A justification section: Semgrep + CodeQL/Joern + LLM Verifier rationale with paper citations", "e": 2.33, "status": "Not Started", "notes": ""},
            {"id": "R.M5.T2", "name": "Write Path B justification section: cost-funnel rationale for each tier with paper citations", "e": 4.50, "status": "Not Started", "notes": ""},
            {"id": "R.M5.T3", "name": "Write Dedup and 5-tier Confidence Scoring justification with triple-path fusion rationale", "e": 2.33, "status": "Not Started", "notes": ""},
            {"id": "R.M5.T4", "name": "Write Differential Indexer justification: hash-based incremental scanning design", "e": 1.25, "status": "Not Started", "notes": ""},
            {"id": "R.M5.T5", "name": "Write PoE Layer justification and compile tech-lead narrative summary (<=2 pages for non-technical stakeholders)", "e": 4.33, "status": "Not Started", "notes": ""},
        ],
    },
    {
        "id": "R.M6",
        "name": "Ongoing Research Monitoring",
        "type": "MILESTONE",
        "start": "2026-07-14",
        "end": "2026-08-01",
        "o": 3.5, "ml": 8.5, "p": 19.0, "e": 9.42,
        "status": "Not Started",
        "notes": "Set up alert infrastructure for post-June-2026 papers. Forward-citation pass on top 5 most-cited papers.",
        "tasks": [
            {"id": "R.M6.T1", "name": "Configure arXiv email digest alerts for all 7 research areas using category filters cs.CR, cs.SE, cs.LG", "e": 1.08, "status": "Not Started", "notes": ""},
            {"id": "R.M6.T2", "name": "Configure Google Scholar keyword alerts for ZeroTrust.sh-relevant terms", "e": 1.08, "status": "Not Started", "notes": ""},
            {"id": "R.M6.T3", "name": "Perform forward-citation pass on top 5 most-cited papers in the 40-paper catalogue", "e": 3.33, "status": "Not Started", "notes": ""},
            {"id": "R.M6.T4", "name": "Write monitoring runbook documenting exact search queries, weekly review steps, monthly deep-search protocol", "e": 2.17, "status": "Not Started", "notes": ""},
            {"id": "R.M6.T5", "name": "Integrate newly discovered papers into validation matrix; update benchmarks reference table if figures superseded", "e": 1.75, "status": "Not Started", "notes": ""},
        ],
    },
]
