constraints_data = [
    {
        "id": "C-01",
        "constraint": "Developer has no prior Go experience entering G2",
        "category": "Experience",
        "impact": "High",
        "applied_to": "G2 (M1-M3); G3 (all milestones)",
        "buffer_added": "+20% applied to ML estimate on all Go-first tasks in G2 M1-M3",
        "notes": "AI assistance (Copilot / Claude Code) estimated to reduce effective learning time by 40-60% vs. unaided learning. Buffer not reduced — AI reduces blocked-state duration, not probability.",
    },
    {
        "id": "C-02",
        "constraint": "8-week internship window (Jun 9 – Aug 1, 2026) at approximately 6 productive hours per day",
        "category": "Time",
        "impact": "High",
        "applied_to": "All goals",
        "buffer_added": "Total capacity: ~240 h. Allocated: ~300 h PERT E across all goals. Research milestones interleaved with implementation.",
        "notes": "Research milestones (R.M1-R.M6) are designed to be interleaved with implementation work, not sequential. Research reading occurs during low-energy periods; coding during peak focus hours.",
    },
    {
        "id": "C-03",
        "constraint": "G1 tech lead presentation is fixed at 2026-06-27 — this date cannot slip",
        "category": "Time",
        "impact": "High",
        "applied_to": "G1 (all milestones)",
        "buffer_added": "None — date is immovable. Stretch items cut first if M1.4 runs late.",
        "notes": "If M1.4 (Finding Schema) is not complete by Jun 26 EOD, any stretch work is automatically cancelled. Demo recording fallback must exist before Jun 26.",
    },
    {
        "id": "C-04",
        "constraint": "G2 Path A checkpoint targeted for 2026-07-18",
        "category": "Time",
        "impact": "Medium",
        "applied_to": "G2 (M4)",
        "buffer_added": "2.BUF (13h) provides absorption window.",
        "notes": "Date is soft — can slip 1-2 days if integration testing reveals critical bugs. Must not slip past Jul 21 (G3 start date).",
    },
    {
        "id": "C-05",
        "constraint": "Demo deadline is 2026-08-06; submission cutoff is 2026-08-08",
        "category": "Time",
        "impact": "High",
        "applied_to": "G4 (all milestones)",
        "buffer_added": "4.BUF (3h) is the only buffer. No slack beyond Aug 8.",
        "notes": "G4 is 34h of PERT E in 5 days. Pre-stub of SSVC dedup skeleton and HTML report shell during G3 final week (Jul 28-31) is required to meet this deadline.",
    },
    {
        "id": "C-06",
        "constraint": "Ollama LLM runtime requires a 4-8 GB quantized GGUF model download before any LLM task in G2 can begin",
        "category": "Tool",
        "impact": "Medium",
        "applied_to": "G2 (M3: LLM Verifier; M3: LLM Semantic Scan)",
        "buffer_added": "0.5 day pre-setup buffer built into the Jun 30 sprint start",
        "notes": "Model: CodeLlama-7B-Instruct or Mistral-7B-Instruct-v0.2 (recommended). Download must happen before Jul 11 (M3 start date). Corporate network proxy settings may add setup time.",
    },
    {
        "id": "C-07",
        "constraint": "G4 PoE Layer (4.M4) requires Docker Desktop installed and running on the development machine",
        "category": "Environment",
        "impact": "Medium",
        "applied_to": "G4 (M4: Docker Sandbox) — stretch only",
        "buffer_added": "0.5 day installation buffer included in 4.M4 PERT E estimate",
        "notes": "Corporate machines may have Docker Desktop blocked by IT policy. Fallback: use Podman (drop-in replacement with same Docker SDK API). Verify Docker availability on Aug 1.",
    },
    {
        "id": "C-08",
        "constraint": "Semgrep CLI version must be pinned in all demo scripts to ensure reproducible output across machines",
        "category": "Tool",
        "impact": "Low",
        "applied_to": "G1 (M1: rule suite); G4 (M3: demo prep)",
        "buffer_added": "1 h included in demo prep tasks to handle version verification",
        "notes": "Semgrep YAML rule syntax can differ between minor versions. Pin to the version used during rule development. Document in demo/README.md.",
    },
    {
        "id": "C-09",
        "constraint": "Mentor/tech lead review cycles take 2-3 business days per round",
        "category": "Dependency",
        "impact": "Medium",
        "applied_to": "All goals — presentation milestones and architecture decisions",
        "buffer_added": "Explicit buffer rows in each goal absorb review wait time",
        "notes": "Architecture sign-off for G2/G3 is gated on G1 tech lead approval (Jun 27). Submit G1 materials at least 2 days before Jun 27 to allow feedback incorporation.",
    },
    {
        "id": "C-10",
        "constraint": "Detailed planning for G2 and G3 is deferred until the G1 tech lead presentation is approved",
        "category": "Dependency",
        "impact": "Medium",
        "applied_to": "G2 (start gate); G3 (start gate)",
        "buffer_added": "G2 officially starts Jun 30 — 3 days after the G1 presentation, allowing for feedback incorporation.",
        "notes": "If G1 tech lead requests major scope changes, G2 milestones may need to be re-estimated. The 3-day gap (Jun 27-30) is intentionally left as a planning and adjustment window.",
    },
]
