goal4_data = [
    {
        "id": "4.M1",
        "name": "Dedup + SSVC Confidence Scoring",
        "type": "MILESTONE",
        "start": "2026-08-01",
        "end": "2026-08-03",
        "o": 6, "ml": 10, "p": 16, "e": 10.3,
        "status": "Not Started",
        "notes": "Skeleton should be pre-stubbed during G3 final week; merges Path A + Path B findings into unified 5-tier output",
        "tasks": [
            {"id": "4.M1.T1", "name": "Dedup — AST edit distance comparison", "e": 2.0, "status": "Not Started", "notes": "Compare evidence snippets from Path A and Path B; collapse duplicates above edit-distance threshold"},
            {"id": "4.M1.T2", "name": "Dedup — CWE pattern hash", "e": 1.5, "status": "Not Started", "notes": "Hash: CWE ID + file path + line range; collapse findings with identical hash; fastest dedup pass, runs first"},
            {"id": "4.M1.T3", "name": "Dedup — LLM semantic similarity check (Python worker call)", "e": 2.0, "status": "Not Started", "notes": "For findings not collapsed by T1/T2: embed + cosine similarity; collapse if similarity > threshold"},
            {"id": "4.M1.T4", "name": "SSVC dimension mapping -> 5-tier score assignment", "e": 2.0, "status": "Not Started", "notes": "Dimensions: Exploitation (EPSS from OSV), Automatable (taint path), Technical Impact (sink type); map to BLOCK/HIGH/MEDIUM/LOW/SUPPRESSED"},
            {"id": "4.M1.T5", "name": "Cross-path confirmation boost (+15% for findings confirmed by both paths)", "e": 1.0, "status": "Not Started", "notes": "If same finding appears in Path A and Path B output (after dedup): boost SSVC score by +15%"},
            {"id": "4.M1.T6", "name": "Suppression rules + dedup test suite", "e": 1.8, "status": "Not Started", "notes": "Suppress: findings in test files (_test.go, test_*.py), framework-safe functions; test suite: 5+ dedup cases, 3+ suppression"},
        ],
    },
    {
        "id": "4.M2",
        "name": "HTML Report Generator + Patch Suggestions",
        "type": "MILESTONE",
        "start": "2026-08-03",
        "end": "2026-08-04",
        "o": 6, "ml": 10, "p": 16, "e": 10.3,
        "status": "Not Started",
        "notes": "Go html/template + embed only — no Python dependency; output is a single portable .html file",
        "tasks": [
            {"id": "4.M2.T1", "name": "Go html/template structure + embed setup", "e": 3.0, "status": "Not Started", "notes": "//go:embed templates/*; base template with header, severity sections, finding cards; CSS inlined; no CDN dependencies"},
            {"id": "4.M2.T2", "name": "Finding list serialization to HTML (severity groups, collapsible evidence panels)", "e": 2.0, "status": "Not Started", "notes": "Group findings by SSVC tier (BLOCK first); each finding card: file + line, CWE, rationale, evidence snippet, patch suggestion"},
            {"id": "4.M2.T3", "name": "Filter/sort controls (vanilla JS — no framework)", "e": 2.5, "status": "Not Started", "notes": "Filter by: severity tier, CWE, file path; sort by: SSVC score, file name; ~50 lines of vanilla JS; self-contained"},
            {"id": "4.M2.T4", "name": "SSVC score visualization (severity tier badges + dimension breakdown)", "e": 1.0, "status": "Not Started", "notes": "Colored badge per tier (BLOCK=red, HIGH=orange, MEDIUM=yellow, LOW=blue, SUPPRESSED=grey); tooltip shows SSVC dimensions"},
            {"id": "4.M2.T5", "name": "Patch suggestion prompt template + unified diff output (Python worker call)", "e": 1.8, "status": "Not Started", "notes": "Zero-shot LLM call via `patch_suggest` type; prompt: finding rationale + code context; output: unified diff"},
        ],
    },
    {
        "id": "4.M3",
        "name": "End-to-End Demo Run + Hardening",
        "type": "MILESTONE",
        "start": "2026-08-04",
        "end": "2026-08-06",
        "o": 6, "ml": 10, "p": 16, "e": 10.3,
        "status": "Not Started",
        "notes": "Final gate before demo; `zerotrust scan ./target` must work end-to-end; timing must be < 10 min on test codebase",
        "tasks": [
            {"id": "4.M3.T1", "name": "Source or build 2-3 realistic AI-generated vulnerable codebases", "e": 2.5, "status": "Not Started", "notes": "Languages: Python (FastAPI/Flask), Go (net/http), Java (Spring Boot); use real AI-agent-generated code where possible"},
            {"id": "4.M3.T2", "name": "Full pipeline run on each target codebase", "e": 2.0, "status": "Not Started", "notes": "Run `zerotrust scan ./target` end-to-end; verify: GGUF verified at startup, dirty files only re-scanned, HTML report generated"},
            {"id": "4.M3.T3", "name": "Integration break fixes", "e": 2.0, "status": "Not Started", "notes": "Resolve any pipeline failures from T2; if a fix exceeds 2h, escalate as At Risk; do not introduce new features"},
            {"id": "4.M3.T4", "name": "Scan timing measurement (wall clock + per-component breakdown)", "e": 1.0, "status": "Not Started", "notes": "Instrument: CPG build time, classifier gate time, LLM call time, total wall clock; target total < 10 min"},
            {"id": "4.M3.T5", "name": "Demo script + rehearsal run", "e": 2.8, "status": "Not Started", "notes": "Script covers: detection found, cost funnel % reached LLM, SSVC score explanation, patch diff, model integrity demo"},
        ],
    },
    {
        "id": "4.M4",
        "name": "PoE Layer — Red Team Agent + Docker Sandbox",
        "type": "STRETCH",
        "start": "2026-08-04",
        "end": "2026-08-06",
        "o": None, "ml": None, "p": None, "e": 15.0,
        "status": "Not Started",
        "notes": "STRETCH — CUT FIRST. Do not attempt if any G3 M3.4 task is incomplete on Aug 1. Parallel with M4.3 if attempted.",
        "tasks": [
            {"id": "4.M4.T1", "name": "[STRETCH] LangGraph workflow setup (Recon -> Exploit -> Verify graph nodes)", "e": 4.0, "status": "Not Started", "notes": "Python LangGraph v1.0; 3 nodes with typed state: Reconnaissance, Exploitation, Verification; state machine transitions"},
            {"id": "4.M4.T2", "name": "[STRETCH] Docker sandbox: container spec + seccomp profile (network isolation)", "e": 3.5, "status": "Not Started", "notes": "Go Docker SDK; container: no network, no root, seccomp deny-list; volume mount: target codebase read-only"},
            {"id": "4.M4.T3", "name": "[STRETCH] Docker sandbox: attempt-trigger logic for BLOCK/HIGH findings", "e": 3.5, "status": "Not Started", "notes": "LangGraph Exploitation node generates exploit code; passes to sandbox; captures execution result; timeout = 30s"},
            {"id": "4.M4.T4", "name": "[STRETCH] Two-layer PoE output (technical trace + executive summary)", "e": 2.5, "status": "Not Started", "notes": "Technical trace: exploit code, execution log, sandbox exit code; executive summary: vulnerability name, business impact"},
            {"id": "4.M4.T5", "name": "[STRETCH] Static-evidence fallback when sandbox execution fails", "e": 1.5, "status": "Not Started", "notes": "If sandbox exits non-zero or times out: emit 'Static evidence only — sandbox execution failed'; degrade gracefully"},
        ],
    },
    {
        "id": "4.BUF",
        "name": "G4 Buffer",
        "type": "BUFFER",
        "start": "2026-08-01",
        "end": "2026-08-06",
        "o": None, "ml": None, "p": None, "e": 3.0,
        "status": "",
        "notes": "Tight 10% buffer; primary absorption: integration breaks in M4.3; if M4.4 not attempted, its 15h become additional buffer",
        "tasks": [],
    },
]
