goal1_data = [
    {
        "id": "1.M1",
        "name": "Semgrep + ast-grep Rule Suite",
        "type": "MILESTONE",
        "start": "2026-06-11",
        "end": "2026-06-16",
        "o": 14, "ml": 20, "p": 30, "e": 20.7,
        "status": "In Progress",
        "notes": "Python rules in progress (per CLAUDE.md); Java rules not yet started",
        "tasks": [
            {"id": "1.M1.T1", "name": "Build synthetic vulnerable test codebase (Python + Java)", "e": 3.0, "status": "In Progress", "notes": "Must exist before rules can be validated; trigger every rule class"},
            {"id": "1.M1.T2", "name": "Semgrep rules — LLM prompt injection patterns", "e": 2.0, "status": "In Progress", "notes": "Python rules in progress; cover direct + indirect injection"},
            {"id": "1.M1.T3", "name": "Semgrep rules — security-control bypass comments", "e": 1.5, "status": "Not Started", "notes": "e.g. # nosec, // nolint, AI-inserted disable comments"},
            {"id": "1.M1.T4", "name": "Semgrep rules — hardcoded AI API keys", "e": 1.5, "status": "Not Started", "notes": "OpenAI, Anthropic, Cohere, HuggingFace key patterns"},
            {"id": "1.M1.T5", "name": "Semgrep rules — MCP server config injection (.mcp.json)", "e": 2.0, "status": "Not Started", "notes": "Novel surface; no community rules exist; highest-priority unique claim"},
            {"id": "1.M1.T6", "name": "Semgrep rules — agent instruction file injection (.cursor/rules, AGENTS.md, CLAUDE.md, GEMINI.md, copilot-instructions.md)", "e": 2.5, "status": "Not Started", "notes": "First tool to cover this vector; key demo talking point"},
            {"id": "1.M1.T7", "name": "ast-grep structural matching rules (languages with weak Semgrep community packs)", "e": 3.0, "status": "Not Started", "notes": "YAML rule format; target Rust, Kotlin, C# gaps in Semgrep OSS packs"},
            {"id": "1.M1.T8", "name": "Rule validation + false-positive audit against test codebase", "e": 3.0, "status": "Not Started", "notes": "Each rule must fire on >= 1 test case; zero FPs on a clean-code control"},
            {"id": "1.M1.T9", "name": "CI-runnable test harness", "e": 2.2, "status": "Not Started", "notes": "Makefile or shell script; pass/fail output per rule class; runs in < 60s"},
        ],
    },
    {
        "id": "1.M2",
        "name": "Go CLI Core",
        "type": "MILESTONE",
        "start": "2026-06-16",
        "end": "2026-06-20",
        "o": 12, "ml": 18, "p": 26, "e": 18.3,
        "status": "Not Started",
        "notes": "Claude Code compresses ML est. ~35%; single binary from day one",
        "tasks": [
            {"id": "1.M2.T1", "name": "Go module init + project directory structure", "e": 1.0, "status": "Not Started", "notes": "Go 1.22+; cmd/, internal/, pkg/ layout; add .gitignore"},
            {"id": "1.M2.T2", "name": "CLI argument parsing + TOML config schema", "e": 3.0, "status": "Not Started", "notes": "cobra + viper (or stdlib flag); config fields: model-path, output-dir, scan-target, log-level"},
            {"id": "1.M2.T3", "name": "Directory walk + file-type detection (language routing table)", "e": 3.0, "status": "Not Started", "notes": "filepath.WalkDir; extension -> language enum map; respect .gitignore"},
            {"id": "1.M2.T4", "name": "ZIP archive extract + ingestion path", "e": 2.0, "status": "Not Started", "notes": "archive/zip; extract to OS temp dir; cleanup on exit (defer)"},
            {"id": "1.M2.T5", "name": "Pluggable Finding channel interface definition", "e": 3.5, "status": "Not Started", "notes": "chan Finding or writer interface; all pipeline components write here; schema frozen after M1.4"},
            {"id": "1.M2.T6", "name": "Cross-compile build pipeline (darwin/linux/windows, amd64/arm64)", "e": 2.0, "status": "Not Started", "notes": "Makefile targets; GoReleaser optional; verify binary size < 20 MB"},
            {"id": "1.M2.T7", "name": "Smoke test on real directory + binary install verification", "e": 3.8, "status": "Not Started", "notes": "Binary accepts path arg, scans synthetic codebase, exits 0; test on macOS + Linux"},
        ],
    },
    {
        "id": "1.M3",
        "name": "Ingestion Layer — Model Integrity Verifier + Differential Indexer",
        "type": "MILESTONE",
        "start": "2026-06-20",
        "end": "2026-06-25",
        "o": 12, "ml": 18, "p": 28, "e": 18.7,
        "status": "Not Started",
        "notes": "MIV is a unique security property vs all competitors; demo talking point",
        "tasks": [
            {"id": "1.M3.T1", "name": "Model Integrity Verifier: SHA256 hash function for GGUF file", "e": 1.0, "status": "Not Started", "notes": "crypto/sha256; stream file in chunks to avoid OOM on large (4-8 GB) models"},
            {"id": "1.M3.T2", "name": "Model Integrity Verifier: pinned manifest format + loader", "e": 2.0, "status": "Not Started", "notes": "JSON manifest: model name, version, expected SHA256; bundled in binary via go:embed"},
            {"id": "1.M3.T3", "name": "Model Integrity Verifier: startup check — block scan + user-facing error on mismatch", "e": 2.0, "status": "Not Started", "notes": "Exit code 1 + clear error message; never silently continue on mismatch"},
            {"id": "1.M3.T4", "name": "Differential Indexer: per-file hash computation", "e": 2.0, "status": "Not Started", "notes": "xxHash (faster) or SHA256 per file; parallel via goroutines over file list"},
            {"id": "1.M3.T5", "name": "Differential Indexer: hash cache store", "e": 2.5, "status": "Not Started", "notes": "BoltDB at ~/.zerotrust/cache/<project-hash>.db; JSON flat-file as fallback"},
            {"id": "1.M3.T6", "name": "Differential Indexer: dirty-file computation (current vs cached hash diff)", "e": 2.0, "status": "Not Started", "notes": "Returns []FileEntry of changed + new files only; passes to pipeline entry point"},
            {"id": "1.M3.T7", "name": "Differential Indexer: cache update on successful scan completion", "e": 1.5, "status": "Not Started", "notes": "Only write on clean exit (code 0); never persist partial scan state"},
            {"id": "1.M3.T8", "name": "Integration test: tampered GGUF file -> scan blocked", "e": 2.5, "status": "Not Started", "notes": "Flip one byte in model file; assert exit code 1 + correct error message"},
            {"id": "1.M3.T9", "name": "Integration test: repeat scan -> only changed files re-scanned", "e": 3.2, "status": "Not Started", "notes": "Full scan, modify 1 file, rescan; assert only modified file enters pipeline"},
        ],
    },
    {
        "id": "1.M4",
        "name": "Canonical Finding Schema + CLI Output",
        "type": "MILESTONE",
        "start": "2026-06-25",
        "end": "2026-06-27",
        "o": 6, "ml": 10, "p": 16, "e": 10.3,
        "status": "Not Started",
        "notes": "Schema locked after this milestone — no breaking changes in G2/G3/G4",
        "tasks": [
            {"id": "1.M4.T1", "name": "Finding struct definition in Go", "e": 2.0, "status": "Not Started", "notes": "Fields: CWE, Severity, File, LineStart, LineEnd, Source, Confidence, Evidence, TaintPath (omitempty)"},
            {"id": "1.M4.T2", "name": "Severity tier constants (BLOCK / HIGH / MEDIUM / LOW / SUPPRESSED)", "e": 0.5, "status": "Not Started", "notes": "Typed string constants — not bare strings; use in all components"},
            {"id": "1.M4.T3", "name": "JSON serialization for Finding struct", "e": 2.0, "status": "Not Started", "notes": "encoding/json; omitempty on optional fields; test marshal/unmarshal roundtrip"},
            {"id": "1.M4.T4", "name": "Human-readable stdout formatter (colorized, grouped by severity)", "e": 3.0, "status": "Not Started", "notes": "BLOCK=red, HIGH=orange, MEDIUM=yellow, LOW=blue; respect NO_COLOR env var"},
            {"id": "1.M4.T5", "name": "Unit tests: struct construction, JSON serialization, stdout output", "e": 2.8, "status": "Not Started", "notes": "Table-driven tests; golden file for stdout formatter output"},
        ],
    },
    {
        "id": "1.BUF",
        "name": "G1 Buffer",
        "type": "BUFFER",
        "start": "2026-06-11",
        "end": "2026-06-27",
        "o": None, "ml": None, "p": None, "e": 10.0,
        "status": "",
        "notes": "Absorbs: Joern env surprises (R-01), tool version mismatches, sick days; cut stretch items before touching buffer",
        "tasks": [],
    },
]
