goal3_data = [
    {
        "id": "3.M1",
        "name": "Heuristic Targeting + Call Graph + CVE Enrichment",
        "type": "MILESTONE",
        "start": "2026-07-21",
        "end": "2026-07-25",
        "o": 12, "ml": 18, "p": 28, "e": 18.7,
        "status": "Not Started",
        "notes": "Reads Joern CPG from G2 (no re-parse); Trivy replaced by OSV-Scanner (CVE-2026-33634 supply chain compromise)",
        "tasks": [
            {"id": "3.M1.T1", "name": "CPG node-type queries — external-input nodes", "e": 2.5, "status": "Not Started", "notes": "Query CPG for HTTP params, env vars, file reads, stdin, deserialized objects; language-agnostic via shared CPG schema"},
            {"id": "3.M1.T2", "name": "CPG node-type queries — auth-boundary nodes", "e": 2.0, "status": "Not Started", "notes": "Identify authentication/authorization check points; missing guard detection starts here"},
            {"id": "3.M1.T3", "name": "CPG node-type queries — AI agent config file nodes", "e": 2.0, "status": "Not Started", "notes": "MCP configs, .cursor/rules, AGENTS.md, CLAUDE.md, GEMINI.md; unique detection surface"},
            {"id": "3.M1.T4", "name": "Call graph extraction from Joern CPG", "e": 3.0, "status": "Not Started", "notes": "No separate build step — call graph comes from CPG built in G2; extract caller/callee edges; output: Go CallGraph struct"},
            {"id": "3.M1.T5", "name": "OSV-Scanner Go library integration (github.com/google/osv-scanner/v2)", "e": 3.0, "status": "Not Started", "notes": "Direct Go import — no subprocess; scan dependency manifests (go.mod, requirements.txt, pom.xml, package.json)"},
            {"id": "3.M1.T6", "name": "CVE exact-match auto-flag + routing to findings", "e": 2.0, "status": "Not Started", "notes": "If OSV-Scanner returns exact CVE match -> write Finding directly with severity from CVSS; skip further analysis"},
            {"id": "3.M1.T7", "name": "BOLAZ zero-trust resource ID dataflow flagging", "e": 2.5, "status": "Not Started", "notes": "Flag all external IDs as untrustworthy until explicit authorization confirmed at each function boundary; targets IDOR/BOLA"},
            {"id": "3.M1.T8", "name": "Surface list output format for downstream classifier", "e": 1.7, "status": "Not Started", "notes": "Struct: Surface{ID, File, FunctionName, NodeType, CallGraphDepth, CVEMatches}; passed to M3.2 classifier"},
        ],
    },
    {
        "id": "3.M2",
        "name": "UniXcoder Classifier Gate",
        "type": "MILESTONE",
        "start": "2026-07-25",
        "end": "2026-07-28",
        "o": 12, "ml": 18, "p": 28, "e": 18.7,
        "status": "Not Started",
        "notes": "Primary LLM cost gate; A-18 calibration point — measure real precision/recall on AI-generated code; window spans weekend",
        "tasks": [
            {"id": "3.M2.T1", "name": "UniXcoder model load in Python worker (extend dispatcher)", "e": 2.5, "status": "Not Started", "notes": "Add `classify` type handler to Python worker from G2; load UniXcoder-Base-Nine via transformers; pin model version"},
            {"id": "3.M2.T2", "name": "Go IPC: classify request/response type handling", "e": 2.0, "status": "Not Started", "notes": "Send Surface struct as payload; receive {verdict: vulnerable/safe/uncertain, confidence: float}; reuse NDJSON protocol"},
            {"id": "3.M2.T3", "name": "Confidence threshold calibration (3-band classification)", "e": 3.0, "status": "Not Started", "notes": "Tune thresholds: high-conf-safe (dismiss), high-conf-vulnerable (flag direct), uncertain (-> LLM); target uncertain band = 15-25%"},
            {"id": "3.M2.T4", "name": "High-confidence-safe dismissal routing", "e": 1.5, "status": "Not Started", "notes": "Surfaces below safe threshold -> dropped silently; log count for cost funnel stats used in demo"},
            {"id": "3.M2.T5", "name": "High-confidence-vulnerable direct Finding flag routing", "e": 1.5, "status": "Not Started", "notes": "Surfaces above vulnerable threshold -> write Finding directly to channel; no LLM call; Source field = 'UniXcoder'"},
            {"id": "3.M2.T6", "name": "Unsupported-language bypass (Rust, Kotlin, Swift, C# -> direct LLM)", "e": 1.5, "status": "Not Started", "notes": "UniXcoder trained only on Python/Java/JS/TS/Go/Ruby/PHP; unsupported languages skip classifier"},
            {"id": "3.M2.T7", "name": "A-18 gap measurement: precision/recall on AI-generated code vs BigVul baseline", "e": 3.2, "status": "Not Started", "notes": "Run classifier on test codebase (AI-generated code); record F1, precision, recall; compare to claimed F1=94.73% on BigVul"},
            {"id": "3.M2.T8", "name": "Classifier gate integration test: verify < 25% of surfaces reach LLM tier", "e": 3.5, "status": "Not Started", "notes": "Run full surface set through gate; assert uncertain band <= 25%; if over, re-tune thresholds; log final funnel stats"},
        ],
    },
    {
        "id": "3.M3",
        "name": "Call Chain Context Assembler + Semantic Function Summarizer",
        "type": "MILESTONE",
        "start": "2026-07-28",
        "end": "2026-07-31",
        "o": 12, "ml": 18, "p": 28, "e": 18.7,
        "status": "Not Started",
        "notes": "LLM never receives raw code — only semantic summaries; aligns with IRIS ICLR 2025 design",
        "tasks": [
            {"id": "3.M3.T1", "name": "Call chain traversal to depth 3 from Joern CPG (caller -> surface -> callee)", "e": 4.0, "status": "Not Started", "notes": "Use call graph from 3.M1.T4; traverse depth 3 max; return ordered list [caller, surface, callee]; handle recursive/missing nodes"},
            {"id": "3.M3.T2", "name": "Multi-function context assembly (structured call chain representation)", "e": 3.0, "status": "Not Started", "notes": "Struct: CallChainContext{functions: []FunctionContext, entryPoint, depth}; FunctionContext: name, params, local vars, calls, return type"},
            {"id": "3.M3.T3", "name": "Semantic summary schema — taint-flow vulnerability class", "e": 2.0, "status": "Not Started", "notes": "Fields: untrustedDataSource, sanitizersPresent[], sanitizerGaps[], sinkReached, sinkType"},
            {"id": "3.M3.T4", "name": "Semantic summary schema — auth-guard vulnerability class", "e": 2.0, "status": "Not Started", "notes": "Fields: resourceAccessed, authCheckPresent, authCheckLocation, principalVerified; enables IDOR + missing auth guard detection"},
            {"id": "3.M3.T5", "name": "Semantic summary schema — logic-flaw vulnerability class", "e": 2.0, "status": "Not Started", "notes": "Fields: businessConstraints[], stateTransitions[], enforcedAtBoundary; targets business logic and state machine flaws"},
            {"id": "3.M3.T6", "name": "Function-level semantic abstraction generation (Python worker call)", "e": 2.5, "status": "Not Started", "notes": "For each FunctionContext in call chain: call Python worker with `summarize` type; assemble into SummarizedCallChain struct"},
            {"id": "3.M3.T7", "name": "Token footprint measurement before/after summarization", "e": 1.5, "status": "Not Started", "notes": "Count tokens in raw call chain vs summarized version; target >= 60% token reduction; log in docs/benchmarks/token_footprint.md"},
            {"id": "3.M3.T8", "name": "Multi-function vulnerability detection test (IDOR + missing auth guard)", "e": 1.7, "status": "Not Started", "notes": "Synthetic test: IDOR case spanning caller (no auth check) + surface (uses external ID) + callee (DB lookup); assert detected"},
        ],
    },
    {
        "id": "3.M4",
        "name": "Token Budget Controller + LLM ReAct Scan + Scan Security Context Store",
        "type": "MILESTONE",
        "start": "2026-07-31",
        "end": "2026-08-01",
        "o": 14, "ml": 22, "p": 36, "e": 23.0,
        "status": "Not Started",
        "notes": "T7-T9 are SCSS — explicit DROP CANDIDATES; cut these first if window is tight; ReAct scan works without SCSS",
        "tasks": [
            {"id": "3.M4.T1", "name": "Surface prioritization ranking (CVE score x classifier uncertainty)", "e": 2.5, "status": "Not Started", "notes": "Rank uncertain surfaces: (CVSS score from OSV x (1 - classifier confidence)); highest ranked consume token budget first"},
            {"id": "3.M4.T2", "name": "Hard per-scan token cap enforcement", "e": 2.0, "status": "Not Started", "notes": "Configurable cap (default: 50K tokens per scan); token counter incremented on each LLM call; halt when cap reached"},
            {"id": "3.M4.T3", "name": "ReAct loop — Thought step", "e": 2.5, "status": "Not Started", "notes": "LLM receives: semantic summary + vulnerability class schema; produces Thought: hypothesis + what additional context needed"},
            {"id": "3.M4.T4", "name": "ReAct loop — context-request step (call chain depth + CVE lookup)", "e": 3.0, "status": "Not Started", "notes": "LLM can request: deeper call chain (up to depth 3), CVE DB lookup from OSV-Scanner, or prior inferences from SCSS"},
            {"id": "3.M4.T5", "name": "ReAct loop — Observation -> verdict step", "e": 2.5, "status": "Not Started", "notes": "Max 3 ReAct steps; final step produces verdict; XGrammar enforces JSON schema; write to Finding channel"},
            {"id": "3.M4.T6", "name": "XGrammar schema enforcement on ReAct output (extend Python worker)", "e": 2.0, "status": "Not Started", "notes": "Add `llm_scan` type to Python worker dispatcher; XGrammar JSON schema for ReAct verdict"},
            {"id": "3.M4.T7", "name": "[SCSS DROP FIRST] Scan Security Context Store: in-memory key-value store per scan", "e": 3.0, "status": "Not Started", "notes": "DROP if M3.4 starts late; per-scan map: {surfaceID -> SecurityInference}; stores inferred data sources, sanitizer gaps"},
            {"id": "3.M4.T8", "name": "[SCSS DROP FIRST] SCSS read/write hooks on LLM calls", "e": 2.0, "status": "Not Started", "notes": "DROP if M3.4 starts late; before ReAct Thought: inject prior inferences from SCSS; after verdict: write new inferences"},
            {"id": "3.M4.T9", "name": "[SCSS DROP FIRST] Cross-surface vulnerability detection test", "e": 3.5, "status": "Not Started", "notes": "DROP if M3.4 starts late; test: vulnerability only detectable by combining inferences from two separate surfaces"},
        ],
    },
    {
        "id": "3.BUF",
        "name": "G3 Buffer",
        "type": "BUFFER",
        "start": "2026-07-21",
        "end": "2026-08-01",
        "o": None, "ml": None, "p": None, "e": 8.0,
        "status": "",
        "notes": "Compressed 10% buffer (tight window); SCSS drop saves 8.5h — treat as de-facto buffer extension if M3.4 runs short",
        "tasks": [],
    },
]
