goal2_data = [
    {
        "id": "2.M1",
        "name": "Joern CPG Build Pipeline",
        "type": "MILESTONE",
        "start": "2026-06-30",
        "end": "2026-07-07",
        "o": 16, "ml": 25, "p": 40, "e": 26.0,
        "status": "Not Started",
        "notes": "Highest-risk milestone in plan; Joern env setup is the most common blocker; plan for 1-2 debug days",
        "tasks": [
            {"id": "2.M1.T1", "name": "Joern installation + JVM setup + version-pin", "e": 2.0, "status": "Not Started", "notes": "Pin exact Joern version in config (e.g. v4.x); Java 11+; confirm `joern --version` exits 0"},
            {"id": "2.M1.T2", "name": "Joern server startup verification", "e": 2.5, "status": "Not Started", "notes": "Start Joern in server mode; send a no-op query; confirm response; measure cold-start time"},
            {"id": "2.M1.T3", "name": "Go subprocess wrapper: spawn Joern process via os/exec", "e": 4.0, "status": "Not Started", "notes": "exec.Command; capture stdout/stderr; handle premature exit; log all Joern stderr to debug file"},
            {"id": "2.M1.T4", "name": "Go subprocess wrapper: health check + retry logic", "e": 2.5, "status": "Not Started", "notes": "Poll Joern REST endpoint or REPL; max 3 retries; fail scan with clear error if Joern unresponsive"},
            {"id": "2.M1.T5", "name": "CPG generation: invoke Joern on source directory, capture output", "e": 4.5, "status": "Not Started", "notes": "Feed only dirty files from Differential Indexer; enforce <= 5K LOC gate before invoking; measure build time"},
            {"id": "2.M1.T6", "name": "CPG serialization format decision + implementation", "e": 4.0, "status": "Not Started", "notes": "Decision: in-memory graph vs file-based export; chosen format must be readable by both Path A and Path B without re-parse"},
            {"id": "2.M1.T7", "name": "Shared CPG access interface (Path A + Path B)", "e": 3.5, "status": "Not Started", "notes": "Go interface with at least: QueryNodes(type), QueryEdges(src, dst), GetCallGraph(); G3 components read from this interface"},
            {"id": "2.M1.T8", "name": "Codebase size gate (<= 5K LOC) + query timeout handling", "e": 2.0, "status": "Not Started", "notes": "Count LOC before CPG build; reject with user-facing error if over limit; kill Joern process on timeout (default 60s)"},
            {"id": "2.M1.T9", "name": "Integration test: CPG built successfully on synthetic test codebase", "e": 1.3, "status": "Not Started", "notes": "Assert CPG non-empty; assert node types present (Method, Call, Identifier); assert build time < 30s"},
        ],
    },
    {
        "id": "2.M2",
        "name": "Taint Analysis Query Layer",
        "type": "MILESTONE",
        "start": "2026-07-07",
        "end": "2026-07-11",
        "o": 14, "ml": 22, "p": 34, "e": 22.7,
        "status": "Not Started",
        "notes": "Taint paths produced here are the evidence fed into M2.3 LLM Verifier prompt",
        "tasks": [
            {"id": "2.M2.T1", "name": "Source / sanitizer / sink taxonomy definition per language", "e": 3.0, "status": "Not Started", "notes": "Languages: Java, Python, JS/TS, Go; document each category in a YAML taxonomy file"},
            {"id": "2.M2.T2", "name": "Joern traversal queries: external-input source nodes", "e": 3.5, "status": "Not Started", "notes": "Scala DSL; sources: HTTP params, env vars, file reads, stdin, deserialized objects"},
            {"id": "2.M2.T3", "name": "Joern traversal queries: sanitizer nodes", "e": 3.5, "status": "Not Started", "notes": "Sanitizers: input validation, HTML encoding, parameterized queries, allowlist checks"},
            {"id": "2.M2.T4", "name": "Joern traversal queries: dangerous sink nodes", "e": 3.5, "status": "Not Started", "notes": "Sinks: eval, exec/system, SQL string concat, deserialize, file write to user-controlled path, SSRF URL construction"},
            {"id": "2.M2.T5", "name": "Taint flow -> Finding struct mapping + CWE assignment", "e": 3.5, "status": "Not Started", "notes": "Each taint flow serialized: source node, sanitizer gaps, sink node, traversal path; CWE assigned by sink type"},
            {"id": "2.M2.T6", "name": "Multi-language taint query test suite", "e": 3.0, "status": "Not Started", "notes": "One taint case per language (Java, Python, JS/TS, Go); each must be detected; add to CI harness"},
            {"id": "2.M2.T7", "name": "False positive baseline measurement on synthetic clean code", "e": 2.7, "status": "Not Started", "notes": "Run taint queries on clean-code control set; count FPs; record as baseline before LLM Verifier applied"},
        ],
    },
    {
        "id": "2.M3",
        "name": "Python Worker Bootstrap + LLM Verifier (False Positive Filter)",
        "type": "MILESTONE",
        "start": "2026-07-11",
        "end": "2026-07-16",
        "o": 18, "ml": 29, "p": 42, "e": 29.3,
        "status": "Not Started",
        "notes": "Two parts: (1) IPC boundary — built once, reused by all G3 ML components; (2) LLM Verifier using XGrammar-2",
        "tasks": [
            {"id": "2.M3.T1", "name": "Python venv setup + requirements.txt", "e": 1.5, "status": "Not Started", "notes": "Packages: xgrammar-2 (or xgrammar>=2.0), ollama (Python client), httpx; pin versions; venv at worker/venv/"},
            {"id": "2.M3.T2", "name": "Python worker main.py: message dispatcher", "e": 3.0, "status": "Not Started", "notes": "Reads NDJSON from stdin in a loop; dispatches by `type` field (llm_verify, classify, summarize, llm_scan, ping, shutdown)"},
            {"id": "2.M3.T3", "name": "Go worker-manager: spawn Python worker via os/exec + pipe setup", "e": 3.5, "status": "Not Started", "notes": "exec.Command('python3', '-u', 'worker/main.py'); -u disables output buffering; pipe stdin + stdout; route stderr to log"},
            {"id": "2.M3.T4", "name": "Go worker-manager: health-check ping + restart-on-crash logic", "e": 2.5, "status": "Not Started", "notes": "Send ping; await pong; detect closed stdout pipe; attempt 1 restart; fallback to direct Ollama HTTP on second failure"},
            {"id": "2.M3.T5", "name": "NDJSON protocol: request/response schema + Go client library", "e": 3.0, "status": "Not Started", "notes": "Request: {id, type, payload}; Response: {id, status, result} or {id, status, error}; thread-safe"},
            {"id": "2.M3.T6", "name": "Python worker: Ollama HTTP client integration", "e": 2.5, "status": "Not Started", "notes": "Call Ollama REST API (/api/generate); pass model name from config; handle timeout; verify model loaded"},
            {"id": "2.M3.T7", "name": "Python worker: XGrammar-2 JSON schema enforcement on LLM output", "e": 3.0, "status": "Not Started", "notes": "Verdict JSON schema: {verified: bool, confidence: float, rationale: str}; XGrammar-2 enforces at generation time"},
            {"id": "2.M3.T8", "name": "Taint-flow prompt template", "e": 3.5, "status": "Not Started", "notes": "Template inputs: taint flow path, sink type, reachability condition, sanitizer gaps; test with 5+ real taint flows"},
            {"id": "2.M3.T9", "name": "Verdict routing back to Go Finding channel", "e": 2.0, "status": "Not Started", "notes": "verified=true -> write Finding to channel; verified=false -> discard; confidence score written to Finding.Confidence"},
            {"id": "2.M3.T10", "name": "Latency benchmark: per-finding round-trip time", "e": 2.0, "status": "Not Started", "notes": "Target: < 2s per finding (Go send -> Python -> Ollama -> XGrammar-2 -> Go receive); log p50/p95"},
            {"id": "2.M3.T11", "name": "Accuracy test: TP/FP rate on synthetic taint findings", "e": 2.8, "status": "Not Started", "notes": "Run LLM Verifier on taint findings from M2.2; target >= 88% FP reduction; record as A-18 pre-check"},
        ],
    },
    {
        "id": "2.M4",
        "name": "Path A Integration Test Suite",
        "type": "MILESTONE",
        "start": "2026-07-16",
        "end": "2026-07-18",
        "o": 6, "ml": 10, "p": 16, "e": 10.3,
        "status": "Not Started",
        "notes": "Natural pause point before G3; Joern CPG confirmed as shared infra; mentor review can be scheduled here",
        "tasks": [
            {"id": "2.M4.T1", "name": "Synthetic test case set: 10+ vulnerable functions (one per CWE class)", "e": 3.0, "status": "Not Started", "notes": "CWE classes: CWE-89 SQL injection, CWE-78 OS command injection, CWE-22 path traversal, CWE-502 deserialization, CWE-611 XXE, CWE-918 SSRF, CWE-79 XSS, CWE-327 weak crypto, CWE-798 hardcoded creds, CWE-94 code injection"},
            {"id": "2.M4.T2", "name": "End-to-end pipeline run (ingestion -> Joern -> taint -> LLM Verifier -> Finding output)", "e": 2.0, "status": "Not Started", "notes": "Single `zerotrust scan ./test-codebase` command; all 10+ CWE cases must produce Findings"},
            {"id": "2.M4.T3", "name": "Precision/recall baseline measurement", "e": 2.0, "status": "Not Started", "notes": "Record in docs/benchmarks/g2_baseline.md; this is the baseline G3 Path B will improve on"},
            {"id": "2.M4.T4", "name": "Integration break fixes", "e": 2.0, "status": "Not Started", "notes": "Resolve any failures found in T2/T3; if a fix takes > 4h, escalate as At Risk and consume buffer"},
            {"id": "2.M4.T5", "name": "Performance profiling: full scan time on 5K LOC synthetic codebase", "e": 1.3, "status": "Not Started", "notes": "Measure: CPG build time, taint query time, LLM Verifier time, total wall clock; target total < 5 min on 5K LOC"},
        ],
    },
    {
        "id": "2.BUF",
        "name": "G2 Buffer",
        "type": "BUFFER",
        "start": "2026-06-30",
        "end": "2026-07-18",
        "o": None, "ml": None, "p": None, "e": 13.0,
        "status": "",
        "notes": "Primary risk: R-01 Joern env setup surprises (OOM, Scala DSL learning curve); secondary: mentor review cycle",
        "tasks": [],
    },
]
